INSERT INTO external_payments (
    user_id,
    provider,
    transaction_id,
    merchant_name,
    amount,
    currency,
    transaction_type,
    transaction_date,
    created_at
)
SELECT
    5,
    'SHINHAN',
    CONCAT('tx_nf_', DATE_FORMAT(d, '%Y%m')),
    'NETFLIX',
    14900,
    'KRW',
    'PAYMENT',
    DATE_FORMAT(d, '%Y-%m-01 10:00:00'),
    NOW()
FROM (
         SELECT DATE_ADD('2020-01-01', INTERVAL seq MONTH) AS d
         FROM (
                  SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL
                  SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
                  SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL
                  SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL
                  SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
                  SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL
                  SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL
                  SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
                  SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL
                  SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL
                  SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL
                  SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL
                  SELECT 60 UNION ALL SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL SELECT 64 UNION ALL
                  SELECT 65 UNION ALL SELECT 66 UNION ALL SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL
                  SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL SELECT 73 UNION ALL SELECT 74
              ) t
     ) dates;


INSERT INTO external_payments (
    user_id,
    provider,
    transaction_id,
    merchant_name,
    amount,
    currency,
    transaction_type,
    transaction_date,
    created_at
)
SELECT
    5,
    'KAKAO',
    CONCAT('tx_yt_', DATE_FORMAT(d, '%Y%m')),
    'YOUTUBE',
    9900,
    'KRW',
    'PAYMENT',
    DATE_FORMAT(d, '%Y-%m-05 12:00:00'),
    NOW()
FROM (
         SELECT DATE_ADD('2020-01-01', INTERVAL seq MONTH) AS d
         FROM (
                  SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL
                  SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
                  SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL
                  SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL
                  SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
                  SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL
                  SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL
                  SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
                  SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL
                  SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL
                  SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL
                  SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL
                  SELECT 60 UNION ALL SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL SELECT 64 UNION ALL
                  SELECT 65 UNION ALL SELECT 66 UNION ALL SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL
                  SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL SELECT 73 UNION ALL SELECT 74
              ) t
     ) dates;




INSERT INTO external_payments (
    user_id,
    provider,
    transaction_id,
    merchant_name,
    amount,
    currency,
    transaction_type,
    transaction_date,
    created_at
)
SELECT
    5,
    'TOSS',
    CONCAT('tx_nt_', DATE_FORMAT(d, '%Y')),
    'NOTION',
    100000,
    'KRW',
    'PAYMENT',
    DATE_FORMAT(d, '%Y-03-10 09:00:00'),
    NOW()
FROM (
         SELECT DATE_ADD('2020-03-10', INTERVAL seq YEAR) AS d
         FROM (
                  SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL
                  SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6
              ) t
     ) dates;

INSERT INTO external_payments (
    user_id,
    provider,
    transaction_id,
    merchant_name,
    amount,
    currency,
    transaction_type,
    transaction_date,
    created_at
)
SELECT
    5,
    'KB',
    CONCAT('tx_sp_', DATE_FORMAT(d, '%Y%m')),
    'SPOTIFY',
    10900,
    'KRW',
    'PAYMENT',
    DATE_FORMAT(d, '%Y-%m-07 08:30:00'),
    NOW()
FROM (
         SELECT DATE_ADD('2020-01-01', INTERVAL seq MONTH) AS d
         FROM (
                  SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL
                  SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
                  SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL
                  SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL
                  SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
                  SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL
                  SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL
                  SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
                  SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL
                  SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL
                  SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL
                  SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL
                  SELECT 60 UNION ALL SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL SELECT 64 UNION ALL
                  SELECT 65 UNION ALL SELECT 66 UNION ALL SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL
                  SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL SELECT 73 UNION ALL SELECT 74
              ) t
     ) dates;


INSERT INTO external_payments (
    user_id,
    provider,
    transaction_id,
    merchant_name,
    amount,
    currency,
    transaction_type,
    transaction_date,
    created_at
)
SELECT
    5,
    'NH',
    CONCAT('tx_ic_', DATE_FORMAT(d, '%Y%m')),
    'APPLE.COM/BILL',
    1300,
    'KRW',
    'PAYMENT',
    DATE_FORMAT(d, '%Y-%m-15 02:00:00'),
    NOW()
FROM (
         SELECT DATE_ADD('2020-01-01', INTERVAL seq MONTH) AS d
         FROM (
                  SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL
                  SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL
                  SELECT 10 UNION ALL SELECT 11 UNION ALL SELECT 12 UNION ALL SELECT 13 UNION ALL SELECT 14 UNION ALL
                  SELECT 15 UNION ALL SELECT 16 UNION ALL SELECT 17 UNION ALL SELECT 18 UNION ALL SELECT 19 UNION ALL
                  SELECT 20 UNION ALL SELECT 21 UNION ALL SELECT 22 UNION ALL SELECT 23 UNION ALL SELECT 24 UNION ALL
                  SELECT 25 UNION ALL SELECT 26 UNION ALL SELECT 27 UNION ALL SELECT 28 UNION ALL SELECT 29 UNION ALL
                  SELECT 30 UNION ALL SELECT 31 UNION ALL SELECT 32 UNION ALL SELECT 33 UNION ALL SELECT 34 UNION ALL
                  SELECT 35 UNION ALL SELECT 36 UNION ALL SELECT 37 UNION ALL SELECT 38 UNION ALL SELECT 39 UNION ALL
                  SELECT 40 UNION ALL SELECT 41 UNION ALL SELECT 42 UNION ALL SELECT 43 UNION ALL SELECT 44 UNION ALL
                  SELECT 45 UNION ALL SELECT 46 UNION ALL SELECT 47 UNION ALL SELECT 48 UNION ALL SELECT 49 UNION ALL
                  SELECT 50 UNION ALL SELECT 51 UNION ALL SELECT 52 UNION ALL SELECT 53 UNION ALL SELECT 54 UNION ALL
                  SELECT 55 UNION ALL SELECT 56 UNION ALL SELECT 57 UNION ALL SELECT 58 UNION ALL SELECT 59 UNION ALL
                  SELECT 60 UNION ALL SELECT 61 UNION ALL SELECT 62 UNION ALL SELECT 63 UNION ALL SELECT 64 UNION ALL
                  SELECT 65 UNION ALL SELECT 66 UNION ALL SELECT 67 UNION ALL SELECT 68 UNION ALL SELECT 69 UNION ALL
                  SELECT 70 UNION ALL SELECT 71 UNION ALL SELECT 72 UNION ALL SELECT 73 UNION ALL SELECT 74
              ) t
     ) dates;




INSERT INTO external_payments (
    user_id,
    provider,
    transaction_id,
    merchant_name,
    amount,
    currency,
    transaction_type,
    transaction_date,
    created_at
)
SELECT
    5,
    'SHINHAN',
    CONCAT('tx_conv_', UUID()),
    ELT(1 + FLOOR(RAND()*5),
        'GS25','CU','7-ELEVEN','EMART24','MINISTOP'
    ),
    FLOOR(200 + RAND() * (15000 - 200 + 1)),
    'KRW',
    'PAYMENT',
    DATE_ADD(d, INTERVAL FLOOR(RAND()*24) HOUR),
    NOW()
FROM (
         SELECT DATE_ADD('2020-01-01', INTERVAL seq DAY) AS d
         FROM (
                  SELECT a.seq + b.seq * 10 + c.seq * 100 + d.seq * 1000 AS seq
                  FROM (SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
                           CROSS JOIN (SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
                           CROSS JOIN (SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
                           CROSS JOIN (SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
              ) t
         WHERE seq <= DATEDIFF('2026-03-31', '2020-01-01')
     ) dates
WHERE RAND() < 0.15;

INSERT INTO external_payments (
    user_id,
    provider,
    transaction_id,
    merchant_name,
    amount,
    currency,
    transaction_type,
    transaction_date,
    created_at
)
SELECT
    5,
    'SHINHAN',
    CONCAT('tx_cafe_', UUID()),
    ELT(1 + FLOOR(RAND()*5),
        'STARBUCKS','EDIYA','MEGA COFFEE','PAIKS COFFEE','HOLLYS'
    ),
    FLOOR(4500 + RAND() * (10000 - 4500 + 1)),
    'KRW',
    'PAYMENT',
    DATE_ADD(d, INTERVAL FLOOR(RAND()*24) HOUR),
    NOW()
FROM (
         SELECT DATE_ADD('2020-01-01', INTERVAL seq DAY) AS d
         FROM (
                  SELECT a.seq + b.seq * 10 + c.seq * 100 + d.seq * 1000 AS seq
                  FROM (SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
                           CROSS JOIN (SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
                           CROSS JOIN (SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
                           CROSS JOIN (SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
              ) t
         WHERE seq <= DATEDIFF('2026-03-31', '2020-01-01')
     ) dates
WHERE RAND() < 0.43;


INSERT INTO external_payments (
    user_id,
    provider,
    transaction_id,
    merchant_name,
    amount,
    currency,
    transaction_type,
    transaction_date,
    created_at
)
SELECT
    5,
    'SHINHAN',
    CONCAT('tx_taxi_', UUID()),
    'KAKAO TAXI',
    FLOOR(30000 + RAND() * (50000 - 30000 + 1)),
    'KRW',
    'PAYMENT',
    DATE_ADD(d, INTERVAL FLOOR(RAND()*24) HOUR),
    NOW()
FROM (
         SELECT DATE_ADD('2020-01-01', INTERVAL seq DAY) AS d
         FROM (
                  SELECT a.seq + b.seq * 10 + c.seq * 100 + d.seq * 1000 AS seq
                  FROM (SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
                           CROSS JOIN (SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
                           CROSS JOIN (SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
                           CROSS JOIN (SELECT 0 seq UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
              ) t
         WHERE seq <= DATEDIFF('2026-03-31', '2020-01-01')
     ) dates
WHERE RAND() < 0.14;
