### 구독 단일 조회
GET http://localhost:8080/api/v1/subscriptions/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1Iiwicm9sZSI6IlVTRVIiLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzc0Nzg5MDY2LCJleHAiOjE3NzQ3OTA4NjZ9.dnN075C7os2eg-OBJTPDZiSeVztgiEBuBADUZu31sPM
Content-Type: application/json
